// Bangla Keyboard — Classic (SutonnyMJ / Bijoy ASCII) engine.
//
// Runs the deadkey FSM extracted from macos/.../Bangla Classic.keylayout
// (see classic_table.h, generated by gen_classic.py) using the same Apple
// deadkey algorithm as keylayout_interp.py — so output matches the Mac exactly.
//
// Output is the legacy SutonnyMJ/Bijoy encoding (Latin/​symbol code points that
// render as Bangla *only* in the SutonnyMJ font), NOT Unicode Bangla. The Unicode
// mode lives in engine.h. Strings are std::u16string (every code point is BMP).
#ifndef BANGLA_CLASSIC_H
#define BANGLA_CLASSIC_H

#include <string>

namespace bangla {

class ClassicEngine {
public:
    // Emit text for one key (may be empty while a deadkey is pending). scanCode is
    // the Windows Set-1 scan code; shift = Shift held.
    std::u16string process(unsigned scanCode, bool shift);
    // Emit any dangling deadkey and reset (space / Enter / focus loss / chord).
    std::u16string flush();
    void reset() { state_ = 0; }
    // True if this scan code is part of the Classic layout (else host handles it).
    bool wouldHandle(unsigned scanCode) const;

private:
    int state_ = 0;  // 0 = "none"
};

} // namespace bangla

#endif
