# Emit classic_test.cpp using the validated Python interpreter as ground truth.
import os
from keylayout_interp import KeyLayout, K

def esc(s):
    o = []
    for ch in s:
        cp = ord(ch)
        if ch == '"':  o.append('\\"')
        elif ch == '\\': o.append('\\\\')
        elif 0x20 <= cp < 0x7f: o.append(ch)
        else: o.append('\\u%04x' % cp)
    return 'u"' + ''.join(o) + '"'

here = os.path.dirname(os.path.abspath(__file__))
kl = os.path.join(here, '..', '..', 'macos', 'src', 'keylayouts', 'Bangla Classic.keylayout')
c = KeyLayout(kl)

specs = ['j', 'i', 'm', '^h', '^a', 'z', 'c j', 'd j', 'j m ^a', '^h f n ^a b',
         'h f ^q ^v f', 'd j g ^n', 'i c y g ^y', 'f d m', '^f', 'h ^v', 'c j f',
         'v f i f', 'b f m']  # রাহা-ish, নাম-ish

cases = []
for s in specs:
    cases.append((s, c.type_keys(K(s))))

lines = []
lines.append('// AUTO-GENERATED by gen_classic_test.py — expected = the validated keylayout')
lines.append('// interpreter (ground truth from the macOS Bangla Classic.keylayout).')
lines.append('// Build: g++ -std=c++17 -O2 -static -finput-charset=UTF-8 classic_test.cpp classic.cpp -o classictest && ./classictest')
lines.append('#include "classic.h"')
lines.append('#include <cstdio>')
lines.append('#include <string>')
lines.append('#include <vector>')
lines.append('using bangla::ClassicEngine;')
lines.append('static unsigned scanOf(char c){switch(c){'
             "case '`':return 0x29;case '1':return 0x02;case '2':return 0x03;case '3':return 0x04;"
             "case '4':return 0x05;case '5':return 0x06;case '6':return 0x07;case '7':return 0x08;"
             "case '8':return 0x09;case '9':return 0x0A;case '0':return 0x0B;case '-':return 0x0C;case '=':return 0x0D;"
             "case 'q':return 0x10;case 'w':return 0x11;case 'e':return 0x12;case 'r':return 0x13;case 't':return 0x14;"
             "case 'y':return 0x15;case 'u':return 0x16;case 'i':return 0x17;case 'o':return 0x18;case 'p':return 0x19;"
             "case '[':return 0x1A;case ']':return 0x1B;case '\\\\':return 0x2B;"
             "case 'a':return 0x1E;case 's':return 0x1F;case 'd':return 0x20;case 'f':return 0x21;case 'g':return 0x22;"
             "case 'h':return 0x23;case 'j':return 0x24;case 'k':return 0x25;case 'l':return 0x26;case ';':return 0x27;case '\\'':return 0x28;"
             "case 'z':return 0x2C;case 'x':return 0x2D;case 'c':return 0x2E;case 'v':return 0x2F;case 'b':return 0x30;"
             "case 'n':return 0x31;case 'm':return 0x32;case ',':return 0x33;case '.':return 0x34;case '/':return 0x35;"
             'default:return 0;}}')
lines.append('static std::u16string typeKeys(const std::string& spec){ClassicEngine e;std::u16string out;std::string tok;'
             'auto play=[&](const std::string& t){if(t.empty())return;bool sh=t[0]==\'^\';char k=sh?t[1]:t[0];out+=e.process(scanOf(k),sh);};'
             'for(char ch:spec){if(ch==\' \'){play(tok);tok.clear();}else tok+=ch;}play(tok);out+=e.flush();return out;}')
lines.append('struct Case{const char* spec;const char16_t* expected;};')
lines.append('int main(){')
lines.append('  std::vector<Case> cases = {')
for spec, out in cases:
    lines.append('    {%-18s %s},' % ('"' + spec + '",', esc(out)))
lines.append('  };')
lines.append('  int pass=0;')
lines.append('  for(auto&c:cases){std::u16string g=typeKeys(c.spec);std::u16string e=c.expected;bool ok=(g==e);pass+=ok;')
lines.append('    std::printf("[%s] %-14s -> %d u16 units\\n", ok?"PASS":"FAIL", c.spec, (int)g.size());')
lines.append('    if(!ok){std::printf("      got "); for(char16_t x:g) std::printf("U+%04X ",(unsigned)x);')
lines.append('            std::printf("\\n      exp "); for(char16_t x:e) std::printf("U+%04X ",(unsigned)x); std::printf("\\n");}}')
lines.append('  std::printf("\\n%d/%d passed\\n",pass,(int)cases.size());')
lines.append('  return pass==(int)cases.size()?0:1;')
lines.append('}')

dst = os.path.join(here, 'classic_test.cpp')
with open(dst, 'w', encoding='utf-8') as fh:
    fh.write('\n'.join(lines) + '\n')
print('wrote', dst, 'with', len(cases), 'cases')
