# Generate windows/engine/classic_table.h — the Bangla Classic (SutonnyMJ/Bijoy
# ASCII) deadkey FSM as a C++ table, keyed by Windows scan code. The C++ engine
# (classic.cpp) runs the same Apple-deadkey algorithm as keylayout_interp.py, so
# Classic output matches the macOS .keylayout exactly.
#
#   python gen_classic.py    # writes classic_table.h
import os, sys
from keylayout_interp import KeyLayout

# macOS virtual keycode -> Windows Set-1 scan code (the US-QWERTY positions)
KC2SCAN = {
 0:0x1E,1:0x1F,2:0x20,3:0x21,4:0x23,5:0x22,6:0x2C,7:0x2D,8:0x2E,9:0x2F,11:0x30,
 12:0x10,13:0x11,14:0x12,15:0x13,16:0x15,17:0x14,18:0x02,19:0x03,20:0x04,21:0x05,
 22:0x07,23:0x06,24:0x0D,25:0x0A,26:0x08,27:0x0C,28:0x09,29:0x0B,30:0x1B,31:0x18,
 32:0x16,33:0x1A,34:0x17,35:0x19,37:0x26,38:0x24,39:0x28,40:0x25,41:0x27,42:0x2B,
 43:0x33,44:0x35,45:0x31,46:0x32,47:0x34,50:0x29,
}

def cpp_u16(s):
    out = []
    for ch in s:
        cp = ord(ch)
        if ch == '"':  out.append('\\"')
        elif ch == '\\': out.append('\\\\')
        elif 0x20 <= cp < 0x7F: out.append(ch)
        else: out.append('\\u%04x' % cp)
    return 'u"' + ''.join(out) + '"'

def main():
    here = os.path.dirname(os.path.abspath(__file__))
    kl = os.path.join(here, '..', '..', 'macos', 'src', 'keylayouts', 'Bangla Classic.keylayout')
    L = KeyLayout(kl)

    # intern states (none -> 0) and output strings ("" -> 0)
    states = {'none': 0}
    strings = {'': 0}
    def sid(s):
        if s not in states: states[s] = len(states)
        return states[s]
    def oid(s):
        s = s or ''
        if s not in strings: strings[s] = len(strings)
        return strings[s]

    # Build actions. Direct-output keys become a synthetic 1-rule action.
    # action -> list of (stateId, outId, nextStateId)
    actions = {}            # name -> ruleslist ; synthetic get names "#out:<id>"
    def action_rules(name):
        if name in actions: return name
        rules = []
        for st, (out, nxt) in L.actions.get(name, {}).items():
            rules.append((sid(st), oid(out), sid(nxt) if nxt else 0))
        actions[name] = rules
        return name
    def synth_output(out):
        key = '#o:%d' % oid(out)
        if key not in actions:
            actions[key] = [(0, oid(out), 0)]
        return key

    # keymap[shift][scancode] -> action name
    keymap = {0: {}, 1: {}}
    for shift, idx in ((0, L.base_idx), (1, L.shift_idx)):
        for kc, (kind, val) in L.keymaps.get(idx, {}).items():
            scan = KC2SCAN.get(kc)
            if scan is None: continue
            name = synth_output(val) if kind == 'output' else action_rules(val)
            keymap[shift][scan] = name

    # ensure terminators' and transitions' states are interned, then flatten.
    # (collect any states referenced but not yet interned)
    for name, rules in list(actions.items()):
        for (st, o, nx) in rules: pass
    term = {}
    for st, out in L.terminators.items():
        term[sid(st)] = oid(out)

    # assign action ids in stable order, flatten rules
    anames = list(actions.keys())
    aid = {n: i for i, n in enumerate(anames)}
    flat = []
    aspan = []
    for n in anames:
        aspan.append((len(flat), len(actions[n])))
        for (st, o, nx) in actions[n]:
            flat.append((st, o, nx))

    nstates = len(states)
    # strings table ordered by id
    inv_strings = [None] * len(strings)
    for s, i in strings.items(): inv_strings[i] = s
    # terminator array by state id
    termarr = [0] * nstates
    for st, o in term.items(): termarr[st] = o

    out = []
    out.append('// AUTO-GENERATED by gen_classic.py from macos Bangla Classic.keylayout — do not edit.')
    out.append('// Bangla Classic (SutonnyMJ/Bijoy ASCII) deadkey FSM, keyed by Windows scan code.')
    out.append('#ifndef BANGLA_CLASSIC_TABLE_H')
    out.append('#define BANGLA_CLASSIC_TABLE_H')
    out.append('namespace bangla { namespace classic_table {')
    out.append('struct Rule { short state; short out; short next; };')
    out.append('struct Span { short off; short cnt; };')
    out.append('static const int NSTATES = %d;' % nstates)
    # strings
    out.append('static const char16_t* const STRINGS[] = {')
    out.append('  ' + ', '.join(cpp_u16(s) for s in inv_strings))
    out.append('};')
    out.append('static const int NSTRINGS = %d;' % len(inv_strings))
    # rules
    out.append('static const Rule RULES[] = {')
    line = '  '
    for (st, o, nx) in flat:
        line += '{%d,%d,%d},' % (st, o, nx)
        if len(line) > 110: out.append(line); line = '  '
    if line.strip(): out.append(line)
    out.append('};')
    # action spans
    out.append('static const Span ACTIONS[] = {')
    line = '  '
    for (off, cnt) in aspan:
        line += '{%d,%d},' % (off, cnt)
        if len(line) > 110: out.append(line); line = '  '
    if line.strip(): out.append(line)
    out.append('};')
    # terminators
    out.append('static const short TERM[] = {')
    out.append('  ' + ','.join(str(x) for x in termarr))
    out.append('};')
    # keymap[2][256]
    out.append('static const short KEYMAP[2][256] = {')
    for shift in (0, 1):
        row = [-1] * 256
        for scan, name in keymap[shift].items():
            row[scan] = aid[name]
        out.append('  { ' + ','.join(str(x) for x in row) + ' },')
    out.append('};')
    out.append('}} // namespace')
    out.append('#endif')

    dst = os.path.join(here, 'classic_table.h')
    with open(dst, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(out) + '\n')
    print('wrote', dst)
    print('states=%d strings=%d actions=%d rules=%d' % (nstates, len(inv_strings), len(anames), len(flat)))

if __name__ == '__main__':
    main()
