// AUTO-GENERATED by gen_klengine_test.py — expected = the validated
// keylayout interpreter (ground truth from the macOS .keylayout files).
#include "klengine.h"
#include "unicode_table.h"
#include "classic_table.h"
#include <cstdio>
#include <string>
#include <vector>
using bangla::KLEngine;
static unsigned scanOf(char c){switch(c){case '`':return 0x29;case '1':return 0x02;case '2':return 0x03;case '3':return 0x04;case '4':return 0x05;case '5':return 0x06;case '6':return 0x07;case '7':return 0x08;case '8':return 0x09;case '9':return 0x0A;case '0':return 0x0B;case '-':return 0x0C;case '=':return 0x0D;case 'q':return 0x10;case 'w':return 0x11;case 'e':return 0x12;case 'r':return 0x13;case 't':return 0x14;case 'y':return 0x15;case 'u':return 0x16;case 'i':return 0x17;case 'o':return 0x18;case 'p':return 0x19;case '[':return 0x1A;case ']':return 0x1B;case '\\':return 0x2B;case 'a':return 0x1E;case 's':return 0x1F;case 'd':return 0x20;case 'f':return 0x21;case 'g':return 0x22;case 'h':return 0x23;case 'j':return 0x24;case 'k':return 0x25;case 'l':return 0x26;case ';':return 0x27;case '\'':return 0x28;case 'z':return 0x2C;case 'x':return 0x2D;case 'c':return 0x2E;case 'v':return 0x2F;case 'b':return 0x30;case 'n':return 0x31;case 'm':return 0x32;case ',':return 0x33;case '.':return 0x34;case '/':return 0x35;default:return 0;}}
static std::u16string typeKeys(const bangla::Table* tb,const std::string& spec){KLEngine e(tb);std::u16string out;std::string tok;auto play=[&](const std::string& t){if(t.empty())return;bool sh=t[0]=='^';char k=sh?t[1]:t[0];out+=e.process(scanOf(k),sh);};for(char ch:spec){if(ch==' '){play(tok);tok.clear();}else tok+=ch;}play(tok);out+=e.flush();return out;}
struct Case{const char* spec;const char16_t* expected;};
static int run(const char* name,const bangla::Table* tb,const std::vector<Case>& cs){int pass=0;
  std::printf("== %s ==\n",name);
  for(auto&c:cs){std::u16string g=typeKeys(tb,c.spec);std::u16string e=c.expected;bool ok=(g==e);pass+=ok;
    std::printf("[%s] %-14s\n", ok?"PASS":"FAIL", c.spec);
    if(!ok){std::printf("      got "); for(char16_t x:g) std::printf("U+%04X ",(unsigned)x);
            std::printf("\n      exp "); for(char16_t x:e) std::printf("U+%04X ",(unsigned)x); std::printf("\n");}}
  std::printf("%d/%d\n\n",pass,(int)cs.size());return pass==(int)cs.size();}
int main(){
  std::vector<Case> uni = {
    {"c j",             u"\u0995\u09c7"},
    {"d j",             u"\u0995\u09bf"},
    {"c j f",           u"\u0995\u09c7\u09be"},
    {"^c j",            u"\u0995\u09c8"},
    {"d j g ^n",        u"\u0995\u09cd\u09b7\u09bf"},
    {"i c y g ^y",      u"\u09b9\u099a\u09cd\u099b\u09c7"},
    {"^h f n ^a b",     u"\u09ad\u09be\u09b0\u09cd\u09b8\u09a8"},
    {"j m ^a",          u"\u0995\u09b0\u09cd\u09ae"},
    {"d ^r z",          u"\u09ab\u09cd\u09b0\u09bf"},
    {"h f ^q ^v f",     u"\u09ac\u09be\u0982\u09b2\u09be"},
    {"h ^v",            u"\u09ac\u09b2"},
    {"j f",             u"\u0995\u09be"},
    {"f",               u"\u09be"},
    {"^f",              u"\u0985"},
    {"^f f",            u"\u0986"},
    {"^f f m d",        u"\u0986\u09ae\u09bf"},
    {"d",               u"\u09bf"},
    {"c",               u"\u09c7"},
    {"x",               u"\u0993"},
    {"^f d",            u"\u0985\u09bf"},
  };
  std::vector<Case> cls = {
    {"j",               u"K"},
    {"i",               u"n"},
    {"^h",              u"f"},
    {"c j",             u"\u2021K"},
    {"j m ^a",          u"Kg\u00a9"},
    {"^h f n ^a b",     u"fvm\u00a9b"},
    {"h f ^q ^v f",     u"evsjv"},
    {"d j g ^n",        u"w\u00ff"},
    {"i c y g ^y",      u"n\u2020\u201dQ"},
    {"f",               u"v"},
    {"^f",              u"A"},
    {"h ^v",            u"ej"},
  };
  bool a = run("Bangla Unicode", &bangla::unicode_table::TABLE, uni);
  bool b = run("Bangla Classic", &bangla::classic_table::TABLE, cls);
  return (a&&b)?0:1;
}
